# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AlarmPopUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QLabel
from PyQt5.QtWidgets import QGridLayout, QWidget, QDesktopWidget, QGraphicsView
import pialarm

class Ui_AlarmMessageBox(object):
    def setupUi(self, AlarmMessageBox):
        AlarmMessageBox.setObjectName("AlarmMessageBox")
        AlarmMessageBox.resize(400, 300)
        flags = QtCore.Qt.WindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.WindowStaysOnTopHint)
        AlarmMessageBox.setWindowFlags(flags)
        AlarmMessageBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        qtRectangle = AlarmMessageBox.frameGeometry()
        centerPoint = QDesktopWidget().availableGeometry().center()
        qtRectangle.moveCenter(centerPoint)
        AlarmMessageBox.move(qtRectangle.topLeft())
        self.wakeupmessage = QtWidgets.QLabel(AlarmMessageBox)
        self.wakeupmessage.setGeometry(QtCore.QRect(5, 30, 381, 135))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        self.wakeupmessage.setFont(font)
        self.wakeupmessage.setAlignment(QtCore.Qt.AlignCenter)
        self.wakeupmessage.setWordWrap(True)
        self.wakeupmessage.setObjectName("wakeupmessage")
        self.alarmOffButton = QtWidgets.QPushButton(AlarmMessageBox)
        self.alarmOffButton.setGeometry(QtCore.QRect(0, 190, 401, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.alarmOffButton.setFont(font)
        self.alarmOffButton.setAutoFillBackground(False)
        self.alarmOffButton.setObjectName("alarmOffButton")

        self.alarmOffButton.clicked.connect(program.Ui_MainWindow.end_music)
        self.alarmOffButton.clicked.connect(AlarmMessageBox.close)

        self.retranslateUi(AlarmMessageBox)
        QtCore.QMetaObject.connectSlotsByName(AlarmMessageBox)

    def retranslateUi(self, AlarmMessageBox):
        _translate = QtCore.QCoreApplication.translate
        AlarmMessageBox.setWindowTitle(_translate("AlarmMessageBox", "WAKE UPP!"))
        self.wakeupmessage.setText(_translate("AlarmMessageBox", "<html><head/><body><p align=\"center\">It\'s time to wake up and talk to Zach, your amazing boyfriend who loves you so so much &lt;3</p></body></html>")) #It\'s time to wake up and talk to Zach, your amazing boyfriend who loves you so so much &lt;3
        self.alarmOffButton.setText(_translate("AlarmMessageBox", "Turn Alarm Off"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AlarmMessageBox = QtWidgets.QWidget()
    ui = Ui_AlarmMessageBox()
    ui.setupUi(AlarmMessageBox)
    AlarmMessageBox.setCursor(QtCore.Qt.BlankCursor)
    AlarmMessageBox.show()
    sys.exit(app.exec_())
